version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  typescript-app:
    build: ./typescript-app
    container_name: typescript-app-container
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    ports:
      - "3000:3000"
    volumes:
      - ./typescript-app:/usr/src/app
    networks:
      - backend
    command: ["npm", "run", "dev"]

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
