version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  typescript-app:
    build: .
    container_name: typescript-app-container
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - backend
    command: ["npm", "run", "dev"]

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
